/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package vocb.template

import groovy.text.GStringTemplateEngine
import vocb.ConfHelper
import vocb.Helper

/**
 * @author premik
 *
 */
class Render {


	GStringTemplateEngine templEngine = new GStringTemplateEngine()
		
	ConfHelper cfgHelper = ConfHelper.instance
	@Lazy ConfigObject cfg = cfgHelper.cfg
	Map<String, Boolean> templateVisibility = [:].withDefault {true}
	
	
	public Map getTemplBinding() {
		[cfg:cfg, render: this, template:this.template]
	}
	
	public ConfigObject getTemplate() {		
		cfg.templates[cfg.templateName?:"default"]?:"unknown"
	}


	public String expandTemplate(Object templRes, boolean expandAnkiInterpolations=true) {
		if (!templRes) return ""
		String templResName = templRes as String
		if (!templateVisibility[templResName]) {
			return ""
		}
		String templText = cfgHelper.resolveRes(templResName)?.text
		if (!templText) throw new FileNotFoundException("Failed to find the requested template '$templResName'", cfgHelper.lookupFolders as String)
		if (expandAnkiInterpolations) 
			templText = Helper.ankiInterpoaltion2GString(templText)
		println templText
		
		Writable templ = templEngine.createTemplate(templText).make(templBinding)
		templ.toString()
	}
	
	static void main(String... args) {
		File f = new File("/tmp/work/template/preview.html")
		if (f.exists()) f.delete()
		new Render().with {
			f << expandTemplate("card1-Foreign2Native")
		}				
		println "Done"
		
	}


}
